"""
populate_minimal_db.py - Loads dummy Excel data into 
_minimal.sql
"""
import os
import psycopg2
import pandas as pd
import numpy as np

# Database connection
conn = psycopg2.connect("postgresql://postgres:password123@localhost:5432/mentorship_db")
cursor = conn.cursor()

print("📊 Loading dummy data from Excel files...")


script_dir = os.path.dirname(os.path.abspath(__file__))

# Load Excel files generated by dummy scripts
mentor_file = os.path.join(script_dir, "dummy_mentor_responses.xlsx")
mentee_file = os.path.join(script_dir, "dummy_mentee_responses.xlsx")

mentors_df = pd.read_excel(mentor_file)
mentees_df = pd.read_excel(mentee_file)


print(f"✅ Loaded {len(mentors_df)} mentors and {len(mentees_df)} mentees")

# ===== INSERT MENTORS =====
print("\n📝 Inserting mentors...")

for idx, row in mentors_df.iterrows():
    # 1. Insert user (only fields that exist in schema_minimal.sql)
    cursor.execute("""
        INSERT INTO users (name, email, role)
        VALUES (%s, %s, 'mentor')
        ON CONFLICT (email) DO NOTHING
        RETURNING user_id
    """, (
        row['Name'],
        row['Personal email address']
    ))
    
    result = cursor.fetchone()
    if not result:
        # User already exists, skip
        print(f"  ⚠️  Skipping duplicate: {row['Personal email address']}")
        continue
    
    user_id = result[0]
    
    # 2. Insert mentor profile (only matching columns)
    cursor.execute("""
        INSERT INTO mentor_profiles (
            user_id, 
            expertise_area, 
            expertise_level,
            max_mentee_capacity, 
            current_mentee_count
        ) VALUES (%s, %s, %s, %s, %s)
        RETURNING mentor_profile_id
    """, (
        user_id,
        row['Main Expertise'],
        int(row['Your Expertise Level (Above Area)']),
        int(row['How many mentees will you be taking?']),
        0  # current_mentee_count starts at 0
    ))
    
    mentor_profile_id = cursor.fetchone()[0]
    
    # 3. Generate and insert combined embedding
    embedding = np.random.randn(384) * 0.1
    embedding = embedding / np.linalg.norm(embedding)  # Normalize
    
    embedding_str = '[' + ','.join(map(str, embedding)) + ']'

    cursor.execute("""
        INSERT INTO embeddings (
            mentor_profile_id, 
            embedding_type, 
            embedding_vector
        ) VALUES (%s, 'combined', %s::vector)
    """, (
        mentor_profile_id,
        embedding_str
    ))

conn.commit()
print(f"✅ Inserted {len(mentors_df)} mentors with embeddings")

# ===== INSERT MENTEES =====
print("\n📝 Inserting mentees...")

for idx, row in mentees_df.iterrows():
    # 1. Insert user
    cursor.execute("""
        INSERT INTO users (name, email, role)
        VALUES (%s, %s, 'mentee')
        ON CONFLICT (email) DO NOTHING
        RETURNING user_id
    """, (
        row['Name'],
        row['Personal email address']
    ))
    
    result = cursor.fetchone()
    if not result:
        print(f"  ⚠️  Skipping duplicate: {row['Personal email address']}")
        continue
    
    user_id = result[0]
    
    # 2. Insert mentee profile
    cursor.execute("""
        INSERT INTO mentee_profiles (
            user_id, 
            main_interest, 
            main_interest_level
        ) VALUES (%s, %s, %s)
        RETURNING mentee_profile_id
    """, (
        user_id,
        row['Main Interest'],
        int(row['Your Expertise Level (Above Area)'])
    ))
    
    mentee_profile_id = cursor.fetchone()[0]
    
    # 3. Generate and insert combined embedding
    embedding = np.random.randn(384) * 0.1
    embedding = embedding / np.linalg.norm(embedding)

    embedding_str = '[' + ','.join(map(str, embedding)) + ']'

    cursor.execute("""
        INSERT INTO embeddings (
            mentee_profile_id, 
            embedding_type, 
            embedding_vector
        ) VALUES (%s, 'combined', %s::vector)
    """, (
        mentee_profile_id,
        embedding_str   
    ))

conn.commit()
print(f"✅ Inserted {len(mentees_df)} mentees with embeddings")

# ===== VERIFICATION =====
print("\n🔍 Verifying data...")

cursor.execute("SELECT COUNT(*) FROM users WHERE role = 'mentor'")
mentor_count = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM users WHERE role = 'mentee'")
mentee_count = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM embeddings WHERE embedding_type = 'combined'")
embedding_count = cursor.fetchone()[0]

print(f"  Users (mentors): {mentor_count}")
print(f"  Users (mentees): {mentee_count}")
print(f"  Combined embeddings: {embedding_count}")

cursor.close()
conn.close()

print("\n✅ Database populated successfully!")
print("🚀 Ready to run: python test_matching.py")
